osx_image: xcode11.0
language: objective-c
#xcode_project: delete2.xcodeproj
#xcode_scheme: delete2

env:
  global:
  - PROJECT=delete2
  - SCHEME=delete2
  - OS=11.4
  - DEVICE="iPhone 8"

script:
  - set -o pipefail && xcodebuild -project $PROJECT.xcodeproj -scheme $SCHEME -sdk iphonesimulator -destination "platform=iOS Simulator,OS=$OS,name=$DEVICE" test | xcpretty
