#os: osx
osx_image: xcode11
language: swift
#xcode_project: delete2.xcodeproj
#xcode_scheme: delete2

env:
  global:
  - PROJECT=delete2
  - SCHEME=delete2
  - OS=13.0
  - DEVICE="iPhone 8"

#script: xcodebuild clean build test -workspace delete2.xcodeproj/project.xcworkspace -scheme "delete2" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=11.4,name=iphone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO

script:
  - set -o pipefail && xcodebuild -project $PROJECT.xcodeproj -scheme $SCHEME -sdk iphonesimulator -destination "platform=iOS Simulator,OS=$OS,name=$DEVICE" test | xcpretty
