osx_image: xcode11
language: swift

env:
  global:
  - PROJECT=delete2
  - SCHEME=delete2
  - OS=13.0
  - DEVICE="iPhone 8"

script:
  - set -o pipefail && xcodebuild -project $PROJECT.xcodeproj -scheme $SCHEME -sdk iphonesimulator -destination "platform=iOS Simulator,OS=$OS,name=$DEVICE" test | xcpretty
